### ISSUE TITLE
Will there be any swift3 version?

### ISSUE THREAD

**Issue by nawar** [polok/UICheckbox.Swift#2]
The title says it all. I like your library, and I can convert it but just wondering if you have that in mind?

**Comment by polok** [comment]
Hey,

Yes, I have. I will do this next week or you need this earlier? 

Regards,

**Comment by nawar** [comment]
No rush, whenever you can. :bowing_man:

**Comment by polok** [comment]
Done ;)
Version 1.0.0

**Comment by polok** [comment]
I am going to close the issue.
